name: EcoJourney
description: Earn GreenPoints as you travel with public transport.
version: 1.0.0+1
author: RuntimeTerror
repository: https://github.com/ShivamGoyal1899/EcoJourney

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  intro_slider: ^2.2.7
  font_awesome_flutter: ^8.4.0
  firebase_auth: ^0.14.0+2
  google_sign_in: ^4.0.6
  cloud_firestore: ^0.12.9
  flutter_facebook_login: ^2.0.1
  http: ^0.12.0+2
  autocomplete_textfield: ^1.7.3
  flutter_html: ^0.10.4
  material_design_icons_flutter: 3.2.4096
  camera:
  path_provider:
  path:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 900
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 300
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 700